import re
import os
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.colors import HexColor


def generate_pdf(
    video_title: str,
    channel_name: str,
    published_at: datetime,
    video_url: str,
    summary: str,
    sections: list[dict],
    output_dir: str,
) -> str:
    os.makedirs(output_dir, exist_ok=True)
    safe_title = re.sub(r'[^\w\s-]', '', video_title)[:50].strip()
    filename = f"{safe_title}_{published_at.strftime('%Y%m%d')}.pdf"
    filepath = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(filepath, pagesize=letter,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'],
                                  fontSize=18, spaceAfter=6)
    meta_style = ParagraphStyle('Meta', parent=styles['Normal'],
                                 fontSize=10, textColor=HexColor('#666666'))
    section_title_style = ParagraphStyle('SectionTitle', parent=styles['Heading2'],
                                          fontSize=14, spaceBefore=12)
    body_style = styles['BodyText']
    timestamp_style = ParagraphStyle('Timestamp', parent=styles['Normal'],
                                      fontSize=10, textColor=HexColor('#0066cc'),
                                      spaceBefore=8)

    elements = []

    # Header
    elements.append(Paragraph(_escape(video_title), title_style))
    elements.append(Paragraph(f"{_escape(channel_name)} | {published_at.strftime('%B %d, %Y')}", meta_style))
    elements.append(Paragraph(f"<link href='{video_url}'>{_escape(video_url)}</link>", meta_style))
    elements.append(Spacer(1, 12))

    # Summary
    elements.append(Paragraph("<b>Summary</b>", styles['Heading2']))
    elements.append(Paragraph(_escape(summary), body_style))
    elements.append(Spacer(1, 12))

    # Timestamped sections
    if sections:
        elements.append(Paragraph("<b>Timestamps</b>", styles['Heading2']))
        for sec in sections:
            ts = sec.get("timestamp", "")
            title = sec.get("title", "")
            desc = sec.get("description", "")
            elements.append(Paragraph(f"<b>{_escape(ts)} — {_escape(title)}</b>", section_title_style))
            elements.append(Paragraph(_escape(desc), body_style))

    # Footer
    elements.append(Spacer(1, 24))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                   fontSize=8, textColor=HexColor('#999999'))
    elements.append(Paragraph(
        f"Generated by YT Summarizer on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        footer_style
    ))

    doc.build(elements)
    return filepath


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
